package com.nuvio.tv.ui.screens.player
import com.nuvio.tv.data.local.*
import org.junit.Assert.*
import org.junit.Test
class PlayerControlIntegrationTest {
 private val vod=PlaybackTimelineState(duration=90_000)
 private fun available(state:PlayerUiState=PlayerUiState(playbackIssueReportsEnabled=false),timeline:PlaybackTimelineState=vod,native:Boolean=false,applied:Boolean=false)=playerControlAvailability(state,timeline,native,applied)
 private fun only(vararg actions:PlayerControlAction):PlayerControlLayout { var l=PlayerControlLayout.default(); for(a in PlayerControlAction.entries) l=l.withVisibility(a,a in actions); return l }
 private fun episode()=NextEpisodeInfo("e",1,2,"Next",null,null,null,true,unairedMessage=null)
 @Test fun `saved audio subtitle and episode buttons do not invent content support`() { val a=available(); assertFalse(PlayerControlAction.AUDIO in a); assertFalse(PlayerControlAction.SUBTITLES in a); assertFalse(PlayerControlAction.EPISODES in a); assertFalse(PlayerControlAction.NEXT_EPISODE in a) }
 @Test fun `actual audio subtitle and episode state enables independent buttons`() { val s=PlayerUiState(audioTracks=listOf(TrackInfo(0,"Audio",null)),subtitleTracks=listOf(TrackInfo(0,"Subtitles",null)),currentSeason=1,currentEpisode=1,nextEpisode=episode()); val a=available(s); assertTrue(a.containsAll(setOf(PlayerControlAction.AUDIO,PlayerControlAction.SUBTITLES,PlayerControlAction.EPISODES,PlayerControlAction.NEXT_EPISODE))) }
 @Test fun `native eligibility is not used as selected renderer support`() { assertTrue(PlayerControlAction.SPEED in available(native=false)); assertFalse(PlayerControlAction.SPEED in available(native=true)); assertTrue(PlayerControlAction.PLAY_PAUSE in available(native=true)) }
 @Test fun `applied tunneling and existing requested guard both suppress unsupported actions`() { for(a in listOf(available(applied=true),available(PlayerUiState(tunnelingEnabled=true)))) { assertFalse(PlayerControlAction.SPEED in a); assertFalse(PlayerControlAction.ASPECT in a) } }
 @Test fun `MPV retains working speed even with tunneling preference or stale Exo state`() { val mpv=PlayerUiState(internalPlayerEngine=InternalPlayerEngine.MVP_PLAYER,tunnelingEnabled=true); assertTrue(PlayerControlAction.SPEED in available(mpv,native=true,applied=true)) }
 @Test fun `live and unknown timelines do not expose restart`() { assertFalse(PlayerControlAction.RESTART in available(timeline=PlaybackTimelineState())); assertFalse(PlayerControlAction.RESTART in available(timeline=vod.copy(isLive=true))); assertTrue(PlayerControlAction.RESTART in available()) }
 @Test fun `sending or sent reports never become dead focus targets`() { for(status in listOf(PlaybackIssueReportStatus.Sending,PlaybackIssueReportStatus.Sent)) assertFalse(PlayerControlAction.REPORT in available(PlayerUiState(playbackIssueReportsEnabled=true,playbackIssueReportStatus=status))); assertTrue(PlayerControlAction.REPORT in available(PlayerUiState(playbackIssueReportsEnabled=true))) }
 @Test fun `pending or unaired next episode is unavailable`() { val next=episode(); assertFalse(PlayerControlAction.NEXT_EPISODE in available(PlayerUiState(nextEpisode=next,postPlayMode=PostPlayMode.AutoPlay(next,searching=true)))); assertFalse(PlayerControlAction.NEXT_EPISODE in available(PlayerUiState(nextEpisode=next.copy(hasAired=false)))); assertFalse(PlayerControlAction.NEXT_EPISODE in available(PlayerUiState(nextEpisode=next,postPlayMode=PostPlayMode.AutoPlay(next,countdownSec=1)))) }
 @Test fun `hidden play pause returns to a configured supported target`() { val f=PlayerCustomFocusState(); val l=only(PlayerControlAction.SOURCES); f.restore(l,available()); assertEquals(PlayerControlAction.SOURCES,f.requested) }
 @Test fun `all hidden returns no button target for timeline or container`() { val f=PlayerCustomFocusState(); f.restore(only(),available()); assertNull(f.requested); assertEquals(1,f.requestGeneration) }
 @Test fun `panel return losing capability uses visible fallback`() { val f=PlayerCustomFocusState(); val l=only(PlayerControlAction.AUDIO,PlayerControlAction.SOURCES); f.pendingReturn=PlayerControlAction.AUDIO; f.restore(l,available()); assertEquals(PlayerControlAction.SOURCES,f.requested); assertNull(f.pendingReturn) }
 @Test fun `shared IDs preserve panel target in either style and mixed groups`() { val f=PlayerCustomFocusState(); val l=only(PlayerControlAction.STATS,PlayerControlAction.SPEED,PlayerControlAction.SOURCES).withGroup(PlayerControlAction.SPEED,PlayerControlGroup.CENTRE); f.pendingReturn=PlayerControlAction.SPEED; f.restore(l,available()); assertEquals(PlayerControlAction.SPEED,f.requested); assertEquals(listOf(PlayerControlAction.SPEED),l.visibleGroups(available()).getValue(PlayerControlGroup.CENTRE)) }
 @Test fun `hiding More does not hide independently configured advanced controls`() { val f=PlayerCustomFocusState(); val l=only(PlayerControlAction.SPEED); f.pendingReturn=PlayerControlAction.SPEED; f.restore(l,available()); assertEquals(PlayerControlAction.SPEED,f.requested); assertFalse(PlayerControlAction.MORE in l.focusOrder(available())) }
 @Test fun `focus requesters survive regrouping and recovery`() { val f=PlayerCustomFocusState(); val target=f.target(PlayerControlAction.SOURCES); f.restore(only(PlayerControlAction.SOURCES).withGroup(PlayerControlAction.SOURCES,PlayerControlGroup.CENTRE),available()); assertSame(target,f.target(PlayerControlAction.SOURCES)); f.restore(only(),available()); assertSame(target,f.target(PlayerControlAction.SOURCES)) }
}
